# .github/workflows/main.yml

name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: 7ce689c7e7ab94e1ad477141ea55ebcfd6324828
          source-directory: dist/ngx-vis-network-etsisi-showcase
          build-command: npm run build:showcase
